### ISSUE TITLE
VOLUME /config/www/gallery/galleries instead of /pictures ?

### ISSUE THREAD

**Issue by jodumont** [linuxserver/docker-piwigo#10]
Hi Sparkyballs and the rest of the LinuxServer teams;

Tell me if i'm wrong but I was trying to **import/sync** my photos
and the only way I succeed it is by pointing
all my photos inside `/config/www/gallery/galleries/`

So I wonder what it the purpose of the `VOLUME /pictures`
and why `/config/www/gallery/galleries` is not considered as a mounting point.

**Comment by sparklyballs** [comment]
since /config is already a mount point then any subfolder of /config is by default also in the mount point and there is no need to mount any subfolder separately unless you wish to have the picture folder on a separate drive etc

the /pictures volume in the Dockerfile is superfluous tbh

**Comment by gene1wood** [comment]
@sparklyballs I also got confused by the `/pictures` mount in the `Dockerfile`.

Would you be open to either a PR that removes the mount or a PR to the README that talks about where photos get stored (`/config/www/gallery/galleries/`)?
