### ISSUE TITLE
php-curl and php-ctype

### ISSUE THREAD

**Issue by tchabaud** [linuxserver/docker-piwigo#15]
Hi,

Is it possible to include the php7-curl and php7-ctype extension in this Dockerfile ?

php7-curl is needed for [Piwigo social extension](http://piwigo.org/ext/extension_view.php?eid=684)
php7-ctype is needed to avoid an error if *Send password by email* option is checked during install.

**Comment by cybermcm** [comment]
2nd that, need php7-ctype for mail sending...

**Comment by homerr** [comment]
Pleased to announce this was sorted in #21 - sorry for the delay.
