### ISSUE TITLE
FTP/Upload?

### ISSUE THREAD

**Issue by negativzeroe** [linuxserver/docker-piwigo#17]
All of the sync and ftp tools don't work. How can I upload directory structure? What volume do I need to expose?

**Comment by CHBMB** [comment]
Closing this as there's nowhere near enough detail nor information to give a sensible reply.

@negativzeroe If you still have issues, please open another issue and document what you've tried, as I'm not sure if this is an issue with the container, which we can look at, or an issue with the upstream project.

Thanks
