### ISSUE TITLE
Include ffmpeg and other packages for video support

### ISSUE THREAD

**Issue by georg90** [linuxserver/docker-piwigo#23]
Can you include ffmpeg and other libraries as described here:  https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos

This will be a great benefit if someone wants to support videos as well, it's 2019 ;-)

Thanks for looking into this!!

**Comment by thelamer** [comment]
@georg90 Please test `lsiodev/piwigo:latest` and confirm functionality. 

Also need to know where and how paths need to be set in the application configuration and plugin settings so that  information can be added to the documentation. 

sys bins added: 
```
/usr/bin/ffmpeg
/usr/bin/exiftool
/usr/bin/mediainfo
/usr/bin/jpegtran
/usr/bin/pdftoppm
```

**Comment by georg90** [comment]
@thelamer Thanks for the quick response.

I tested the branch and it works as expected :-)

I had to adjust a little to get the thumbnails to work:

- It doesn't work with the latest version of the VideoJS plugin. Version 2.8b works: https://github.com/xbgmsharp/piwigo-videojs/tree/2.8.b

However, I now get errors parsing the metadata, but I think thats an issue with the VideoJS plugin, I will open an issue over there.

Other than that, it works as expected. Can this be merged in the official master?

**Comment by thelamer** [comment]
As soon as you can explain any changes that are needed to get thumbnails working so we can either make those changes by default or include them in the readme. Also would be nice to get a confirmed working config for videojs to know where the problem lies.

Trust me it is better to iron stuff out here than to pull in unfinished changes .

**Comment by georg90** [comment]
The issue lies within videoJS (for my installation). When trying to generate the thumbnails it will throw and error message and not generate the thumbnails.

The request here, to include the necessary libraries is separated from this in my opinion (since it could be used by other plugins as well). 

To get thumbnailing working, you would only need to manually install version 2.8b (this worked for me). The libraries are automatically found and work OOTB. I posted into the relevant issues at the videojs repo: https://github.com/xbgmsharp/piwigo-videojs/issues/153

The videoJS stuff could be only relevant to my installation and since it's separated, I think we can still pull the changes?

**Comment by thelamer** [comment]
I am talking about config related stuff, did you need to make changes to your config files or in the web interface to leverage mediainfo ffmpeg etc ?

**Comment by georg90** [comment]
Nope, just install the version 2.8b, files are recognized automatically.
