### ISSUE TITLE
web 403 Forbidden nginx/1.16.0

### ISSUE THREAD

**Issue by firexbox** [linuxserver/docker-piwigo#26]
# docker run --name=piwigo -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -p 29080:80 --restart unless-stopped  linuxserver/piwigo
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
........................................................+++++
.+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-install: executing...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168  100   168    0     0    256      0 --:--:-- --:--:-- --:--:--   256
[/tmp/piwigo.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/piwigo.zip or
        /tmp/piwigo.zip.zip, and cannot find /tmp/piwigo.zip.ZIP, period.
mv: cannot stat '/tmp/piwigo/*': No such file or directory
cp: cannot stat '/config/www/gallery/include/config_default.inc.php': No such file or directory
[cont-init.d] 40-install: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by j0nnymoe** [comment]
You're missing the `/config` mount.

**Comment by firexbox** [comment]
> You're missing the `/config` mount.

no difference with the /config mount.

**Comment by aptalca** [comment]
Downloading piwigo during start fails in your log

**Comment by aptalca** [comment]
@firexbox I just created a fresh container and it downloaded the zip just fine. Try again, you may have been having an intermittent issue. Or your container has general internet connectivity issues

**Comment by aptalca** [comment]
#27 downloads zip during build, but you still need to fix your connection issue to get updates, etc.
