### ISSUE TITLE
Can't connect to site.

### ISSUE THREAD

**Issue by millionart** [linuxserver/docker-piwigo#28]
docker Standalone 19.03.4 

> version: "2"
> services:
>   piwigo:
>     image: linuxserver/piwigo
>     container_name: piwigo
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=Europe/London
>     volumes:
>       - /srv/dev-disk-by-label-4T/piwigo:/config
>     ports:
>       - 8080:8080
>     restart: unless-stopped
----

User uid:    1000

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

using keys found in /config/keys

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] 40-install: executing... 

[cont-init.d] 40-install: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

**Comment by j0nnymoe** [comment]
You've ignored the questions in the issue template. Please provide us with the information we ask for.
