### ISSUE TITLE
The upload_max_filesize is too low

### ISSUE THREAD

**Issue by valmar** [linuxserver/docker-piwigo#30]
The value of upload_max_filesize defined in the php.ini file is very low (2M). This causes the upload of big pictures from the android app to fail with the error message: "Failed to move uploaded file".

Please see: https://github.com/Piwigo/Piwigo-Android/issues/217

I suggest increasing it a bit. Currenly, as I workaround, I override the value by setting it in the php-local.ini file, which is persisted across restarts of the container

**Comment by ChildLearningClub** [comment]
I have increased both the upload_max_filesize and post_max_size in the php-local.ini file and restarted the container, phpinfo reflects that it has changed so I know it's seeing the changes. No matter what the settings, I get an Error file too large when trying to upload anything greater than 1 Gigabyte on the web form? Uploading large files from the ios app gives similar issues. I have both piwigo and nextcloud sitting behind nginx reverse proxy and nextcloud has no problem so I assume it's piwigo configuration.

**Comment by hardwareadictos** [comment]
same issue here...

**Comment by hardwareadictos** [comment]
please, can someone show some light on this? That's limiting a lot the Piwigo experience using videojs plugin and using it alongside with DSLR cams which generate big raw/jpeg files.

**Comment by j0nnymoe** [comment]
Don't comment on closed issues when you've already opened an issue.

**Comment by hardwareadictos** [comment]
No problem on it but please, give some help on the already opened issue. There's no news about it since April
