### ISSUE TITLE
Mobile app does not work with this implementation

### ISSUE THREAD

**Issue by maltokyo** [linuxserver/docker-piwigo#33]
Site works perfectly in browser, no complaints at all, and I love it!  

But the mobile apps (both andriod and ios) dont work.  They log in without issue, but all photos and album thumbnails etc are a white square, and no content is visible.  Any hints welcome!

**Comment by LisichkinVlad** [comment]
> Site works perfectly in browser, no complaints at all, and I love it!
> 
> But the mobile apps (both andriod and ios) dont work. They log in without issue, but all photos and album thumbnails etc are a white square, and no content is visible. Any hints welcome!

Had the same problem. For me solution was to use proxy directly to 443 port and use certs directly from swag container.
**piwigo.conf**
       `set $upstream_app piwigo;
        set $upstream_port 443;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;`
**swag docker-compose.yml** (create ssl volume, to use in other containers):
`version: "2.1"
volumes:
  ssl:
    name: ssl
services:
    swag:    
           volumes:
                - ssl:/config/etc`
**piwigo docker-compose.yml**
`version: "2.1"
volumes:
  ssl:
    external: true
services:
   piwigo:
      volumes:
           - ssl:/ssl
      expose:
           - 443`
**Then in piwigo create links to correct certs**
`docker-compose exec piwigo mv /config/keys/cert.key{,.bak};
docker-compose exec piwigo mv /config/keys/cert.crt{,.bak};
docker-compose exec piwigo ln -s /swag_ssl/letsencrypt/live/l1s1.com/privkey.pem /config/keys/cert.key;
docker-compose exec piwigo ln -s /swag_ssl/letsencrypt/live/l1s1.com/fullchain.pem /config/keys/cert.crt;`
`docker-compose exec piwigo` if You do cmd from host, inside container You don`t need this.

**Comment by vintagefuture** [comment]
Hey,

apps seem to work okay at the moment, only heads up is to use the Piwigo NG android app, as the old Piwigo (still in the store) indeed has the problem you described.
I could not find issues with the iOS app.

**Comment by drizuid** [comment]
Issue template not filled out
upstream bug
fix provided in replies
