### ISSUE TITLE
PHP Notices/Deprecated warnings when going to the Piwigo Home Page

### ISSUE THREAD

**Issue by bmunro-peralex** [linuxserver/docker-piwigo#42]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
No PHP warnings or notices

## Current Behavior
**The Notices Below are shown multiple times, I removed the duplicates**
Deprecated: Array and string offset access syntax with curly braces is deprecated in /config/www/gallery/include/functions_cookie.inc.php on line 72
Notice: Trying to access array offset on value of type null in /config/www/gallery/include/functions_category.inc.php on line 140
Notice: Trying to access array offset on value of type null in /config/www/gallery/include/functions_category.inc.php on line 141
Warning: Cannot modify header information - headers already sent by (output started at /config/www/gallery/include/functions_category.inc.php:141) in /config/www/gallery/include/page_header.php on line 101

## Steps to Reproduce
1. Open Piwigo Home Page

## Environment
OS: Docker
CPU architecture: x86_64
Docker Image: linuxserver/piwigo:11.4.0-ls108

**Comment by stonics** [comment]
No one else seeing this issue? I see these messages right after the initial setup

**Comment by Roxedus** [comment]
Missing info, assuming this is a upstream issue.

**Comment by yllekz** [comment]
I'm also getting crazy errors during a brand new install. Is this container broken?:

Deprecated
: Invalid characters passed for attempted conversion, these have been ignored in
/gallery/include/template.class.php
on line
215


Deprecated
: Invalid characters passed for attempted conversion, these have been ignored in
/gallery/include/template.class.php
on line
1024

**Comment by j0nnymoe** [comment]
@yllekz please don't comment on a closed old closed issue. Please open a fresh one with the information requested in the template.
