### ISSUE TITLE
Getting error - Deprecated: Invalid characters passed for attempted conversion, these have been ignored in /gallery/include/template.class.php on line 215

### ISSUE THREAD

**Issue by rmiddle** [linuxserver/docker-piwigo#50]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Steps to Reproduce

1. Install template or Arm32 OS
2. Connect to mysql system and run the installer
3. Get error on the page. 

## Environment
**OS:**
Pi OS bullseye 32
**CPU architecture:** x86_64/arm32/arm64
arm32
**How docker service was installed:**
Pi-Hosted - https://github.com/novaspirit/pi-hosted

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
.............................................................................................+++++
.....+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-install: executing...
[cont-init.d] 40-install: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

================================

Looks like there is an issue for it on the Piwigo issue queue with a fix.

https://github.com/Piwigo/Piwigo/issues/1363

**Comment by Roxedus** [comment]
This sounds like a issue better suited for Piwigo.
