### ISSUE TITLE
No Database setup in Docker Compose

### ISSUE THREAD

**Issue by dipanghosh** [linuxserver/docker-piwigo#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Docker example script does not provide database setup or configuration. This is not explained in the documentation either.

## Current Behavior

The database configuration cannot be set up.

## Alternatives Considered

Docker compose with a database setup.

**Comment by thespad** [comment]
Our compose/run samples are just that, they're not designed to include all the possible configurations with additional containers, which in many cases are 3rd party.

As per Piwigo's [requirements](https://piwigo.org/doc/doku.php?id=user_documentation:learn:install:before) it requires
> MySQL 5 (or the equivalent with MariaDB)

And as per our container documentation
> You must create a user and database for piwigo to use in a mysql/mariadb server.
