### ISSUE TITLE
How to increase max file size correctly.

### ISSUE THREAD

**Issue by hardwareadictos** [linuxserver/docker-piwigo#53]
Good morning.

I just increased those values on php.ini:
post_max_size => 10240M => 10240M
upload_max_filesize => 2048M => 2048M
post_max_size => 10240M => 10240M

From the default 100MB limit just to allow upload my DSLR pics (which are too big) and upload some videos vía videojs plugin but those seems to have no effect:

That's a 1,4GB vídeo:

![image](https://user-images.githubusercontent.com/20403906/189337681-335ac6f1-ff5a-4c84-a69d-362ab4daf322.png)

¿Where are those vars ignored? Using nginx with max_body_size on 0; (unlimited)

Thanks in advance.

**Comment by artoodeetoo2** [comment]
Hi,
The issue is described here
https://piwigo.org/forum/viewtopic.php?id=32008

Modify:
/gallery/admin/themes/default/template/photos_add_direct.tpl

If you need to upload files over 1000mb, raise the max_file_size accordingly

filters : {
                        // Maximum file size
                        max_file_size : '1000mb',
                        // Specify what files to browse for
                        mime_types: [
                                {title : "Image files", extensions : "{/literal}{$file_exts}{literal}"}
                        ]
                },
```
