### ISSUE TITLE
[BUG] Does download arbitrary php files instead of giving a 404

### ISSUE THREAD

**Issue by SebastianSchildt** [linuxserver/docker-piwigo#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried getting piwigo to run, and it "sort of" works (I can initialize the database, get an empty gallery etc.).

However, what is bothering me, is that whenever a wrong/non-existent URL ist accessed it will just ask to download a .php file, I think it is the `index.php`  it starts with

```php
<?php
// +-----------------------------------------------------------------------+
// | This file is part of Piwigo.                                          |
// |                                                                       |
// | For copyright and license information, please view the COPYING.txt    |
// | file that was distributed with this source code.                      |
// +-----------------------------------------------------------------------+

//--------------------------------------------------------------------- include
define('PHPWG_ROOT_PATH','./');
include_once( PHPWG_ROOT_PATH.'include/common.inc.php' );
include(PHPWG_ROOT_PATH.'include/section_init.inc.php')
```

How to reproduce: I tried this directly by exposing the nginx port, no further reverse proxy involved, i.e. doing 

```
    ports:
      - 2222:80
```

and accessing http://127.0.0.1:2222/notexisting

I have the feeling, this might be repaired in the nginx config, but not being an nginx user I could not figure it out

### Expected Behavior

Accesing non-existing files or any other error condition should not trigger the download of a raw php file

### Steps To Reproduce

1. Take the example docker compose
2. Set up DB (not sure this is needed)
3. Access any file that does not exist

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:13.2.0
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - xxx/config:/config
      - xxx/gallery:/gallery
    ports:
      - 2222:80
    restart: unless-stopped


  db:
    image: mariadb
    container_name: piwigo_maria
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=xxx
      - MARIADB_USER=xxx
      - MARIADB_PASSWORD=xxx
    volumes:
      - xxx/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 1111:8080
```

### Container logs

```bash
.
```

**Comment by nemchik** [comment]
Please provide your container logs.

**Comment by LIvewire18** [comment]
My build is doing the same thing. When I check any logs, the only thing that shows up is in /config/log/nginx/access.log as shown below. There is no entry in error.log

access.log entry - 
192.168.25.27 - - [26/Jan/2023:13:22:52 -0600] "GET /notexisting HTTP/2.0" 200 10747 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"

I have not modified anything in the default site or PHP from what is delivered in the pull, and I have no plugins installed. This is pretty much a clean install with a few images added for test.

**Comment by nemchik** [comment]
`docker logs piwigo`

**Comment by LIvewire18** [comment]
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done

**Comment by LIvewire18** [comment]
Is the above what you are looking for? Again, this is an empty, bo additions, build of the container as provided.

**Comment by LIvewire18** [comment]
Is there a chance this will be resolved? I have been looking at it for some time now, and would love to use this image, but cannot. I am an Apache user usually, so I am not familiar with Nginx, but from my research it appear this is related to the default site config. Likely in the location area. However, I haven't made and progress in fixing it on my end.

**Comment by LIvewire18** [comment]
I asked this over on Stack Exchange, and was given an answer that works. Not sure if its the best answer, but it solved all my issues. 

> If a file is not found, try_files $uri $uri/ /index.html /index.php$is_args$args =404; will try to return index.html if it exists or otherwise download index.php. If you want to use 404 when a file is not found, use: try_files $uri $uri/ =404; - see [the try_files documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files)
