### ISSUE TITLE
[BUG] Site isn't working - error 500

### ISSUE THREAD

**Issue by Venkman42** [linuxserver/docker-piwigo#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've set up the piwigo container and a mariadb in docker. I open up the adress for piwigo in a browser and get the installation screen. After entering all the details and clicking on start installation, I just get an error site, saying the page isn't working with http error 500. I tried restarting the container but that didnt help. Theres also no error showing up in the log.

### Steps To Reproduce

Install docker container, open piwigo site and port. Enter details, click on install

### Environment

```markdown
- OS: Raspberry Pi OS(64bit)
- How docker service was installed: portainer stack
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  piwigo:
    image: linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/pi/docker/piwigo/config:/config
      - /home/pi/docker/piwigo/gallery:/gallery
    ports:
      - 32180:80
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Setting resolver to  127.0.0.11
Setting worker_processes to 4
generating self-signed keys in /config/keys, you can replace these with your own keys if required
.+.....+.+.....+...+.............+...+..+.........+..................+.+.....+.+...+...+...+............+..+......+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+..........+...+......+...+..+..........+...........+...+......+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+..+.+..+.......+...+..............+.+.....+............+.......+.........+..+.......+..+...+.+..+.........+....+..+...+....+............+...............+......+.....+...............+.........+................+..+.+.........+...........+..........+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+....+........+...+....+..............+.+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+..+.......+......+..............+......+.+......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+.+.....+....+..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by YouveGotMeowxy** [comment]
Ever get this sorted out? Exact same thing for me. I fill out all the setup stuff and submit, and then just get redirected to `upgrade.php` in the location bar, but it's Error 500.

The database does get populated with the initial stuff, and the bind mounts get populated with the files; I just get stuck at this point.

**Comment by Dummay** [comment]
Same result as described, however in my case redirected to install.php and error 500

**Comment by MikeCook9994** [comment]
> Same result as described, however in my case redirected to install.php and error 500

I suspect you are providing the wrong hostname for the db on the install screen. Assuming you are using docker compose and have the mysql container running alongside the piwigo container, make sure the host name you provide is the name of the database service in the docker compose file.

e.g.:

```yaml
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    ...
  db: <--- this is the name of the database service
    image: mysql
    ...
```

**Comment by fabienpinet** [comment]
I got the same problem. I tried with mariadb and mysql.
With mariadb I got an access denied log error so I did this in the mariadb container:
GRANT ALL ON piwigo.* to 'piwigo'@'%' IDENTIFIED BY 'xxxxx' WITH GRANT OPTION;
It is strange I had to do this but then the install worked, even if the first start was very very long.
Alas the problem isn't totally fixed, now I get an 504 Gateway Time-out when I try to open the admin page.
And i get this error in nginx/error.log:
upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.15.206, server: _, request: "GET /admin.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "piwigo.ill.fr:8080", referrer: "http://piwigo.ill.fr:8080/profile.php"

**Comment by fabienpinet** [comment]
I found the solution for the timeout in the admin page.
We must use a proxy to access outside web sites.
I added it in it php-fpm conf (maybe there is a way to add it directly in the kiwigo conf but without a way to access admin page it's complicated)

In config/php/www2.conf add something like:
env[HTTP_PROXY] =http://xxxx:8888
env[HTTPS_PROXY]=http://xxxx:8888
env[NO_PROXY]   ="localhost,127.0.0.1"

I hope this can help

**Comment by vincemue** [comment]
same for me when trying to install on unraid.
no matter what I put in the details, I only get chrome error message "this site does not work".
No error message from Piwigo.


got these logs from 

<details>

<summary>appdata\piwigo\log\nginx\error.log</summary>

2023/07/10 15:04:41 [error] 312#312: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mysqli::__construct(): Argument #5 ($port) must be of type ?int, string given in /app/www/public/include/dblayer/functions_mysqli.inc.php:52
Stack trace:
#0 /app/www/public/include/dblayer/functions_mysqli.inc.php(52): mysqli->__construct()
#1 /app/www/public/admin/include/functions_install.inc.php(104): pwg_db_connect()
#2 /app/www/public/install.php(260): install_db_connect()
#3 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 52" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:04:55 [error] 312#312: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mysqli::__construct(): Argument #5 ($port) must be of type ?int, string given in /app/www/public/include/dblayer/functions_mysqli.inc.php:52
Stack trace:
#0 /app/www/public/include/dblayer/functions_mysqli.inc.php(52): mysqli->__construct()
#1 /app/www/public/admin/include/functions_install.inc.php(104): pwg_db_connect()
#2 /app/www/public/install.php(260): install_db_connect()
#3 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 52" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:06:47 [error] 312#312: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mysqli::__construct(): Argument #5 ($port) must be of type ?int, string given in /app/www/public/include/dblayer/functions_mysqli.inc.php:52
Stack trace:
#0 /app/www/public/include/dblayer/functions_mysqli.inc.php(52): mysqli->__construct()
#1 /app/www/public/admin/include/functions_install.inc.php(104): pwg_db_connect()
#2 /app/www/public/install.php(260): install_db_connect()
#3 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 52" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:06:57 [error] 312#312: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli::__construct(): php_network_getaddresses: getaddrinfo for mysql failed: Name does not resolve in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 52PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:07:17 [error] 312#312: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli::__construct(): php_network_getaddresses: getaddrinfo for mysql failed: Name does not resolve in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 52PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:08:19 [error] 312#312: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:09:50 [error] 313#313: *21 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:11:46 [error] 300#300: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:12:15 [error] 300#300: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=en_US HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php?language=en_US"
2023/07/10 15:12:21 [error] 300#300: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:12:53 [error] 300#300: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:47:24 [error] 314#314: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/10 15:50:28 [error] 314#314: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=en_US HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php?language=en_US"
2023/07/10 15:52:33 [error] 311#311: *15 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/11 15:58:57 [error] 314#314: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/11 15:59:15 [error] 314#314: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/11 16:00:15 [error] 314#314: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"
2023/07/11 16:02:14 [error] 313#313: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 192.168.178.46, server: _, request: "POST /install.php?language=de_DE HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.200:8280", referrer: "http://192.168.178.200:8280/install.php"

</details>

Am I missing somethin?

**Comment by dubcl** [comment]
Hi, same here, try to install in ubuntu jammy

docker-compose.yml
```
---
version: "2.1"
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/piwigo/config:/config
      - /opt/docker/piwigo/gallery:/gallery
    ports:
      - 8082:80
    links:
      - db
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql
    network_mode: bridge
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: piwigo
      MYSQL_DATABASE: piwigo
      MYSQL_RANDOM_ROOT_PASSWORD: true
```

the nginx error log show this:

```
2023/07/20 17:21:39 [error] 284#284: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on null in /app/www/public/include/dblayer/functions_mysqli.inc.php:88
Stack trace:
#0 /app/www/public/install.php(261): pwg_db_check_charset()
#1 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "POST /install.php?language=en_GB HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "yy.yy.yy.yy:8082", referrer: "http://yy.yy.yy.yy:8082/install.php"
```

same error use de default 80 port.

Regards.

**Comment by contributor** [comment]
I commented out `pwg_db_check_charset()` and install completed sucessfully

**Comment by st0nec0ld** [comment]
Works now ... On install page the db host has to be the name of the mariadb container or the IP + Port. Wasnt self explaning for me.
