### ISSUE TITLE
[BUG] Uploading more than a few photos from Piwigo android app causes container to crash 

### ISSUE THREAD

**Issue by tfmm** [linuxserver/docker-piwigo#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When uploading more than ~5 photos at a time from a Pixel 7 Pro to my fresh installation using this container, the container goes unresponsive and has to be restarted. 

### Expected Behavior

Uploads should complete without issue. 

### Steps To Reproduce

1. Setup Piwigo installation using this container 
2. Create album in Piwigo
3. Install Piwigo Android App
4. Select more than ~5 photos to the album

### Environment

```markdown
- OS:Fedora 38 for server, Android 14 for Android app
- How docker service was installed: Docker-compose, using portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /path/to/data/piwigo/config:/config
      - /path/to/data/piwigo/gallery:/gallery
    ports:
      - 80:80
    restart: unless-stopped

  piwigo-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /path/to/data/piwigo/mariadbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by Ckrtmoezher** [comment]
I am having the same issue, but I am not running piwigo from a container, it is installed in an ARM-64bit system. Whenever I try to upload more than 5 images at a time from the android app, the piwigo server becomes unresponsive. I receive an error message that my photos were not uploaded, and around 10 mins later, the piwigo server becomes responsive aggain. I have configured upload limits of more than 1GB in both PHP, NGINx and piwigo itself, and my photos do not exceed 2-5MB each. Also, I use this ARM based server for other network based work, so it is not a network problem. whenever the piwigo server becomes unresponsive, so does nginx, and I have  corroborated it as I serve other sites through the same nginx instance and all of them are down. not sure if this has to do with piwigo, mysql, nginx, or a combination.

**Comment by homerr** [comment]
Reproduced error and found php process limit being hit. Working on fix.

**Comment by homerr** [comment]
Thanks for the report, issue has been resolved. It may still get a bit moody if you try to do too much at once, given how Piwigo handles the uploads. I tried with 50 and it was OK.
