### ISSUE TITLE
[BUG] Some plugins do not work due to the use of symlinks for plugin directory 

### ISSUE THREAD

**Issue by armanddidierjean** [linuxserver/docker-piwigo#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I'm trying to use this docker image with the plugin [OpenID Connect](https://fr.piwigo.org/ext/extension_view.php?eid=918&rid=7742).
It works with the image `lscr.io/linuxserver/piwigo:13.1.0`, but starting with `lscr.io/linuxserver/piwigo:13.2.0` the plugin does not work :
When I open http://localhost:8080/plugins/OpenIdConnect/auth.php I get an internal error (code 500) instead of being redirected to the auth provider.

The image `13.2.0` correspond, I think, to the addition of the symbolic link `/app/www/public/plugins -> /config/www/plugins`. I believe this is because some modules define relative path, like here [auth.php#L18](https://github.com/jasperweyne/PiwigoOpenIdConnect/blob/2fe22b77b8356d0b7f41d2b6e4e0c8bb58c25c08/auth.php#L18) which doesn't points to the right directory when symbolic links are used.

There is also an issue in Piwigo repository which does not seem up-to-date but which mention incompatibility between symbolic links and some plugins: [Piwigo#907](https://github.com/Piwigo/Piwigo/issues/907)

When I remove the symlink, be deleting the line [init-piwigo-config/run#L50](https://github.com/linuxserver/docker-piwigo/blob/56d696696735e42f25445e48ba0cbeeaef818ff8/root/etc/s6-overlay/s6-rc.d/init-piwigo-config/run#L50), the module works perfectly.

### Expected Behavior

http://localhost:8080/plugins/OpenIdConnect/auth.php shouldn't raise an internal error.

### Steps To Reproduce

1. In Piwigo administration panel, install and enable the plugin [OpenID Connect](https://fr.piwigo.org/ext/extension_view.php?eid=918&rid=7742)
2. Edit the plugin configuration and add an `Issuer URL`, `Client ID` and `Client secret`. Check `Enable Authorization Code Flow` and save settings
3. Logout
4. Try to log in, the server respond with an internal error.

### Environment

```markdown
- OS: macOS 13.6.1
- How docker service was installed: I installed Docker Desktop using [Docker Desktop](https://docs.docker.com/desktop/install/mac-install/) installer
```

### CPU architecture

arm64

### Docker creation

```bash
I use the following Docker compose file:

version: "3"
services:
  piwigo-app:
    image: lscr.io/linuxserver/piwigo:13.8.0
    container_name: piwigo-app
    restart: unless-stopped
    volumes:
      - ./piwigo-app/config:/config
      - ./piwigo-app/gallery:/gallery
    env_file: .env
    networks:
      - piwigo-backend
    ports:
      - 8080:80

  piwigo-db:
    image: mariadb:10.11.2
    container_name: piwigo-db
    restart: unless-stopped
    volumes:
      - ./piwigo-db:/var/lib/mysql
    env_file: .env
    networks:
      - piwigo-backend

networks:
  piwigo-backend:
    name: piwigo-backend
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

In `/config/log/nginx/error.log` there is also an error:
```
2023/11/11 14:52:29 [error] 262#262: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(../../include/common.inc.php): Failed to open stream: No such file or directory in /config/www/plugins/OpenIdConnect/auth.php on line 26PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '../../include/common.inc.php' (include_path='.:/usr/share/php81') in /config/www/plugins/OpenIdConnect/auth.php:26
Stack trace:
#0 {main}
  thrown in /config/www/plugins/OpenIdConnect/auth.php on line 26" while reading response header from upstream, client: 192.168.65.1, server: _, request: "GET /plugins/OpenIdConnect/auth.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8080", referrer: "http://localhost:8080/"
```
```

**Comment by sequent5** [comment]
same problem after upgrade from 13.1.0n to 14.0.0,

**Comment by GD-Dal** [comment]
Same issue her as well. Both v13 and v14

**Comment by GD-Dal** [comment]
Can this be added to the linuxserver Bug and PR Tracker?
Would have nice to see this fixed

**Comment by tfmm** [comment]
Any updates on this one?
