### ISSUE TITLE
[BUG] Update to piwigo 14 doesn't work

### ISSUE THREAD

**Issue by robergej** [linuxserver/docker-piwigo#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When upgraded to the new 14.0 container, the login screen says that an update for the DB to 14 is mandatory. The update seems to be just stuck though, doesn't ever finish, and the application can't open without completing the upgrade.

### Steps To Reproduce

upgrade from 13.8 to 14.0
open piwigo
enter credentials and click upgrade

### Environment

```markdown
- OS: Debian 11 bullseye
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    depends_on:
      - mariadb
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Montreal
      - HTTPS=on
    volumes:
      - ./gallery:/gallery
    ports:
      - 8093:80
    restart: unless-stopped


  mariadb:
    container_name: Piwigo_mariadb
    restart: unless-stopped
    image: arm64v8/mariadb:10.8 # ARM64 IMAGE ONLY, DOES NOT WORK ON ARMv7, AMD or Intel
    command: mysqld --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./database:/var/lib/mysql" # DO NOT REMOVE
    environment:
      TZ: "America/Montreal"
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "piwigo"
      MARIADB_USER: "piwigo"
      MARIADB_PASSWORD: "xxx"
      MARIADB_ROOT_PASSWORD: "xxx"
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    33
User GID:    33
───────────────────────────────────────
using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-10-04 │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by thespad** [comment]
Going to need application/php logs at a minimum to even start trying to troubleshoot what might be happening.

**Comment by robergej** [comment]
I pasted the application logs but I realize there's nothing interesting in them. How do I get php logs?

**Comment by robergej** [comment]
PHP error log:

[10-Dec-2023 02:00:12] NOTICE: fpm is running, pid 354
[10-Dec-2023 02:00:12] NOTICE: ready to handle connections
[12-Dec-2023 08:40:15] NOTICE: Terminating ...
[12-Dec-2023 08:40:16] NOTICE: exiting, bye-bye!
[12-Dec-2023 08:40:56] NOTICE: fpm is running, pid 290
[12-Dec-2023 08:40:56] NOTICE: ready to handle connections
[12-Dec-2023 09:14:00] NOTICE: Terminating ...
[12-Dec-2023 09:14:00] NOTICE: exiting, bye-bye!
[12-Dec-2023 09:14:26] NOTICE: fpm is running, pid 288
[12-Dec-2023 09:14:26] NOTICE: ready to handle connections
[12-Dec-2023 09:48:48] NOTICE: Terminating ...
[12-Dec-2023 09:48:48] NOTICE: exiting, bye-bye!
[12-Dec-2023 09:49:56] NOTICE: fpm is running, pid 290
[12-Dec-2023 09:49:56] NOTICE: ready to handle connections
[12-Dec-2023 10:26:06] NOTICE: Terminating ...
[12-Dec-2023 10:26:06] NOTICE: exiting, bye-bye!
[12-Dec-2023 10:26:32] NOTICE: fpm is running, pid 287
[12-Dec-2023 10:26:32] NOTICE: ready to handle connections

NGINX error log:

2023/12/12 10:26:38 [error] 315#315: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>"
2023/12/12 10:26:41 [error] 314#314: *9 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:26:46 [error] 314#314: *11 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>"
2023/12/12 10:27:01 [error] 314#314: *15 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>"
2023/12/12 10:27:10 [error] 314#314: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '99317' for key 'PRIMARY' in /app/www/public/include/dblayer/functions_mysqli.inc.php:132
Stack trace:
#0 /app/www/public/include/dblayer/functions_mysqli.inc.php(132): mysqli->query()
#1 /app/www/public/install/db/168-database.php(16): pwg_query()
#2 /app/www/public/install/upgrade_13.0.0.php(94): include('...')
#3 /app/www/public/upgrade.php(411): include('...')
#4 {main}
  thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 132" while reading response header from upstream, client: 192.168.128.1, server: _, request: "POST /upgrade.php?language=en_GB HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://photos.<mydomain>/upgrade.php"
2023/12/12 10:27:41 [error] 314#314: *21 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:28:41 [error] 314#314: *25 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:29:42 [error] 314#314: *29 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:30:08 [error] 314#314: *33 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "HEAD /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>"
2023/12/12 10:30:41 [error] 314#314: *37 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:31:41 [error] 315#315: *41 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:32:41 [error] 315#315: *45 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:33:41 [error] 315#315: *49 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:34:41 [error] 315#315: *53 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:35:41 [error] 315#315: *57 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:36:41 [error] 315#315: *61 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:37:41 [error] 315#315: *65 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:38:41 [error] 315#315: *69 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:39:41 [error] 316#316: *73 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:40:41 [error] 316#316: *77 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:41:41 [error] 316#316: *81 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:42:41 [error] 316#316: *85 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:43:41 [error] 316#316: *89 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"
2023/12/12 10:44:41 [error] 316#316: *93 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "RUN_UPGRADE_URL" in /config/www/_data/templates_c/p6jhns^b5737c8ac2ae3123d00bf282c8cb102315a6405c_0.file.upgrade.tpl.php on line 250" while reading response header from upstream, client: 192.168.128.1, server: _, request: "GET /upgrade.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "photos.<mydomain>", referrer: "https://96.21.86.118"

**Comment by thespad** [comment]
Just did a test with 13.8, upgrading to 14.0

![image](https://github.com/linuxserver/docker-piwigo/assets/8425502/ebf2d142-4cc8-4179-b04f-e1e174f21ddc)

![image](https://github.com/linuxserver/docker-piwigo/assets/8425502/e6c334ca-7261-4954-a4a2-50397ca02fed)

Seems to have worked fine. Have you checked your DB container logs to make sure there's nothing awry there?

**Comment by thespad** [comment]
This looks like your actual issue
```
2023/12/12 10:27:10 [error] 314#314: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught mysqli_sql_exception: ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '99317' for key 'PRIMARY' in /app/www/public/include/dblayer/functions_mysqli.inc.php:132
Stack trace:
#0 /app/www/public/include/dblayer/functions_mysqli.inc.php(132): mysqli->query()
https://github.com/linuxserver/docker-piwigo/issues/1 /app/www/public/install/db/168-database.php(16): pwg_query()
https://github.com/linuxserver/docker-piwigo/pull/2 /app/www/public/install/upgrade_13.0.0.php(94): include('...')
https://github.com/linuxserver/docker-piwigo/pull/3 /app/www/public/upgrade.php(411): include('...')
https://github.com/linuxserver/docker-piwigo/pull/4 {main}
thrown in /app/www/public/include/dblayer/functions_mysqli.inc.php on line 132" while reading response header from upstream, client: 192.168.128.1, server: _, request: "POST /upgrade.php?language=en_GB HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "[photos](https://photos/).", referrer: "photos./upgrade.php"
```

**Comment by robergej** [comment]
I agree, but how do I solve this?

**Comment by thespad** [comment]
You probably need to report it to the upstream project, it looks like a failed database migration issue and not something that can be fixed at a container level.

**Comment by robergej** [comment]
Ok thanks
