### ISSUE TITLE
[FEAT] include support for uploading videos from iOS devices

### ISSUE THREAD

**Issue by hkhiro** [linuxserver/docker-piwigo#80]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

used this image to create the initial piwigo container, but it seems in order to support HEVC uploads I have to follow instructions on this [other github project ](https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos). Instructions there require me to include support for ffmpeg and mediainfo. I am not that au fait with docker, but isn't it possible to include these somehow in the compose file? Presumably I then have to install the plugins via piwigo and updates to the script. However, I would also need the actual paths to ffmpeg and mediainfo per instructions there. 

Can anyone help?

### Reason for change

Simplify installation for a simple person

### Proposed code change

no I don't think any code needs changing. Just a guidance on how to support this key use case.

**Comment by aptalca** [comment]
You can install ffmpeg and ffprobe via https://github.com/linuxserver/docker-mods/tree/universal-package-install

The rest of the instructions look like things you can do on piwigo gui
